[dev]
  #  command = "yarn start" # Command to start your dev server
    port = 6557 # Port that the dev server will be listening on
    # publish = "dist" # Folder with the static content for _redirect file

  ## more info on configuring this file: https://ntl.fyi/file-based-build-config
